### ISSUE TITLE
Error in processing text

### ISSUE THREAD

**Issue by mstralenya** [ffalt/xlsx-extract#11] opened 2017-04-17 09:55 UTC
Sometimes lib produces empty string instead of actual strings. I can get right values by changing next lines
```	
       parser.on('text', function (txt) {
		if (addvalue) {
			cell.val = (cell.val ? cell.val : '') + txt;
		}
	});
```

with these 
```	
    parser.on('text', function (txt) {
    console.log(txt);
		//if (addvalue) {
			cell.val = (cell.val ? cell.val : '') + txt;
		//}
	});
```
You can look at file in attachment
[CompetitiveReport_A.xlsx](https://github.com/ffalt/xlsx-extract/files/925302/CompetitiveReport_A.xlsx)

**Comment by ffalt** [comment] 2017-04-19 17:49
Thank you for reporting this bug! This was caused by xlsx-extract not implementing the full cell specification. The demo file you provided showed that strings of [cell type "inlineStr"](http://officeopenxml.com/SScontentOverview.php) have been ignored. 
Excel seems never to save files in that way, but other xlsx libraries do.

Please note: the fix you used has unintended side effects, so don't use that, just update your version. It is fixed in version 0.0.16 on npm.

**Closed by ffalt** 2017-04-19 17:49 UTC
